src/InteractiveGallery.Web/Areas/AdminArea/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InteractiveGallery.Infrastructure.Data;
using InteractiveGallery.Core.ArtistAggregate;
using InteractiveGallery.SharedKernel.Interfaces;
using InteractiveGallery.Core.CategoryAggregate;
using InteractiveGallery.Core.CategoryAggregate.Specifications;
using InteractiveGallery.Core.ArtistAggregate.Specifications;
using Microsoft.AspNetCore.Authorization;

namespace InteractiveGallery.Web.Areas.AdminArea.Controllers;
[Area("AdminArea")]
[Route("AdminArea/[controller]")]
[Authorize(Roles = "Admin")]
public class CategoriesController : Controller
{
  private readonly IRepository<Category> _categoryRepository;


  public CategoriesController(IRepository<Category> categoryRepository)
  {
    _categoryRepository = categoryRepository;
  }

  // GET: Categories
  [HttpGet]
  public async Task<IActionResult> Index()
  {
    var categories = await _categoryRepository.ListAsync();
    return View(categories.ToArray());
  }
  // GET: Categories/Details/5
  [HttpGet("details/{id:int}")]
  public async Task<IActionResult> Details(int id)
  {
    var spec = new CategoryByIdSpec(id);
    var category = await _categoryRepository.FirstOrDefaultAsync(spec);
    if (category == null)
    {
      return NotFound();
    }

    var categoryVO = new CategoryValueObject
    {
      Id = category.Id,
      Name = category.Name,
      Description = category.Description,
    };
    return View(categoryVO);
  }

  // GET: Categories/Create
  [HttpGet("create")]
  public IActionResult Create()
  {
    return View();
  }

  // POST: Categories/Create
  // To protect from overposting attacks, enable the specific properties you want to bind to.
  // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
  [HttpPost("create")]
  [ValidateAntiForgeryToken]
  public async Task<IActionResult> Create(CategoryValueObject categoryValueObject)
  {
    var category = new Category(categoryValueObject);
    if (ModelState.IsValid)
    {
      await _categoryRepository.AddAsync(category);
      await _categoryRepository.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }
    return View(category);
  }

  // GET: Categories/Edit/5
  [HttpGet("edit/{id:int}")]
  public async Task<IActionResult> Edit(int id)
  {
    var spec = new CategoryByIdSpec(id);
    var category = await _categoryRepository.FirstOrDefaultAsync(spec);
    if (category == null)
    {
      return NotFound();
    }
    var categoryVO = new CategoryValueObject
    {
      Id = category.Id,
      Name = category.Name,
      Description = category.Description
    };
    return View(categoryVO);
  }

  // POST: Categories/Edit/5
  // To protect from overposting attacks, enable the specific properties you want to bind to.
  // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
  [HttpPost("edit/{id:int}")]
  [ValidateAntiForgeryToken]
  public async Task<IActionResult> Edit(int id, [Bind("Name,Description,Id")] CategoryValueObject categoryValueObject)
  {
    if (id != categoryValueObject.Id)
    {
      return NotFound();
    }

    if (ModelState.IsValid)
    {
      var spec = new CategoryByIdSpec(id);
      var category = await _categoryRepository.FirstOrDefaultAsync(spec);
      if (category == null) { return NotFound(); }
      category.updateCategory(categoryValueObject);
      await _categoryRepository.UpdateAsync(category);
      await _categoryRepository.SaveChangesAsync();

      return RedirectToAction(nameof(Index));
    }
    return View(categoryValueObject);
  }

  // GET: Categories/Delete/5
  [HttpGet("delete/{id:int}")]
  public async Task<IActionResult> Delete(int id)
  {
    var spec = new CategoryByIdSpec(id);
    var category = await _categoryRepository.FirstOrDefaultAsync(spec);
    if (category == null)
    {
      return NotFound();
    }
    await _categoryRepository.DeleteAsync(category);

    var categoryVO = new CategoryValueObject
    {
      Id = category.Id,
      Name = category.Name,
      Description = category.Description,
    };
    return View(categoryVO);
  }
  // POST: Categories/Delete/5
  [HttpPost("delete/{id:int}")]
  //[HttpPost, ActionName("Delete")]
  [ValidateAntiForgeryToken]
  public async Task<IActionResult> DeleteConfirmed(int id)
  {

    var spec = new CategoryByIdSpec(id);

    var category = await _categoryRepository.FirstOrDefaultAsync(spec);
    if (category != null)
    {
      await _categoryRepository.DeleteAsync(category);
    }

    await _categoryRepository.SaveChangesAsync();
    return RedirectToAction(nameof(Index));
  }

}

src/InteractiveGallery.Web/Areas/UserArea/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InteractiveGallery.Core.ArtistAggregate;
using InteractiveGallery.Infrastructure.Data;
using InteractiveGallery.SharedKernel.Interfaces;
using InteractiveGallery.Core.ArtistAggregate.Specifications;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using InteractiveGallery.Core.GalleryAggregate;
using InteractiveGallery.Core.GalleryAggregate.Specifications;
using InteractiveGallery.Web.ViewModels;
using InteractiveGallery.Core.CategoryAggregate;
using InteractiveGallery.Core.CategoryAggregate.Specifications;

namespace InteractiveGallery.Web.Areas.UserArea.Controllers;

[Area("UserArea")]
[Route("UserArea/[controller]")]
[Authorize(Roles = "User")]
public class ArtistsController : Controller
    {
  private readonly IRepository<Artist> _artistRepository;
  private readonly UserManager<ApplicationUser> _userManager;
  private readonly IRepository<Gallery> _galleryRepository;
  private readonly IRepository<Category> _categoryRepository;
  private readonly IWebHostEnvironment _webHostEnvironment;


  public ArtistsController(IRepository<Artist> artistRepository, UserManager<ApplicationUser> userManager, IRepository<Gallery> galleryRepository, IRepository<Category> categoryRepository, IWebHostEnvironment webHostEnvironment)
  {
    _artistRepository = artistRepository;
    _userManager = userManager;
    _galleryRepository = galleryRepository;
    _categoryRepository = categoryRepository;
    _webHostEnvironment = webHostEnvironment;
  }
   
  [HttpGet]
  public async Task<IActionResult> Index()
  {
    var artists = await _artistRepository.ListAsync();
    return View(artists.ToArray());
  }

  // GET: Artists/Details/5     
  [HttpGet("details/{id:int}")]
  public async Task<IActionResult> Details(int id)
  {
    var spec = new ArtistByIdSpec(id);
    var artist = await _artistRepository.FirstOrDefaultAsync(spec);
    if (artist == null)
    {
      return NotFound();
    }

    var user = _userManager.GetUserAsync(HttpContext.User).Result;
    if (user != null) ViewBag.user = user;

    var artistVO = new ArtistValueObject
    {
      Id = artist.Id,
      Name = artist.Name,
      Biography = artist.Biography,
    };
    var gallerySpec = new GalleryByInitiatorArtistIdSpec(artist.Id);
    artistVO.Galleries = await _galleryRepository.ListAsync(gallerySpec);
    ViewBag.galleries = artistVO.Galleries;
    return View(artistVO);
  }
  [HttpGet("MyArtworks")]
  public async Task<IActionResult> MyArtworks()
  {
    string? identityGuid = _userManager.GetUserId(HttpContext.User);
    var spec = new ArtistByIdentityGuidSpec(identityGuid);
    var artist = await _artistRepository.FirstOrDefaultAsync(spec);
    if (artist == null)
    {
      return NotFound();
    }
    return View(artist);
  }
 


  // GET: Artists/Edit/5
  [HttpGet("editprofile")]
  public async Task<IActionResult> Edit()
  {
    string? identityGuid = _userManager.GetUserId(HttpContext.User);
    var spec = new ArtistByIdentityGuidSpec(identityGuid);
      var artist = await _artistRepository.FirstOrDefaultAsync(spec);
              if (artist == null)
              {
                  return NotFound();
              }
      var artistVO = new ArtistValueObject
      {
        Id = artist.Id,
        Name = artist.Name,
        Biography = artist.Biography
      };
      return View(artistVO);
          }

  // POST: Artists/Edit/5
  // To protect from overposting attacks, enable the specific properties you want to bind to.
  // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
  [HttpPost("editprofile")]
  [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( [Bind("Name,Biography,Id")] ArtistValueObject artistValueObject)
        {
    string? identityGuid = _userManager.GetUserId(HttpContext.User);
    var userSpec = new ArtistByIdentityGuidSpec(identityGuid);
    var artist = await _artistRepository.FirstOrDefaultAsync(userSpec);
    if (artist == null)
    {
      return NotFound();
    }
    if (artist.Id != artistValueObject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                 artist.updateArtist(artistValueObject);
                 await _artistRepository.UpdateAsync(artist);
                 await _artistRepository.SaveChangesAsync();
               
                return RedirectToAction(nameof(Index));
            }
            return View(artistValueObject);
        }

  // GET: Artists/Delete/5
  [HttpGet("delete/{id:int}")]
  public async Task<IActionResult> Delete(int id)
        {

    var spec = new ArtistByIdSpec(id);
    var artist = await _artistRepository.FirstOrDefaultAsync(spec);
    if (artist == null)
    {
      return NotFound();
    }
    await _artistRepository.DeleteAsync(artist);

    var artistVO = new ArtistValueObject
    {
      Id = artist.Id,
      Name = artist.Name,
      Biography = artist.Biography
    };
    return View(artistVO);
  }

  // POST: Artists/Delete/5
  [HttpPost("delete/{id:int}")]
  //[HttpPost, ActionName("Delete")]
 [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
    
    var spec = new ArtistByIdSpec(id);

    var artist = await _artistRepository.FirstOrDefaultAsync(spec);
            if (artist != null)
            {
               await _artistRepository.DeleteAsync(artist);
            }
            
            await _artistRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


  
  //***************************************** Artwork Actions *************************************************
  // GET: Artworks/Create
  [HttpGet("createArtwork")]
  public async Task<IActionResult> CreateArtworkAsync()
  {
    string? identityGuid = _userManager.GetUserId(HttpContext.User);
    var spec = new ArtistByIdentityGuidSpec(identityGuid);
    var artist = await _artistRepository.FirstOrDefaultAsync(spec);
    if (artist == null)
    {
      return NotFound();
    }
    var gallerySpec = new GalleryByInitiatorArtistIdSpec(artist.Id);
    var galleries = await _galleryRepository.ListAsync(gallerySpec);
    List<SelectListItem> selectListGalleries = galleries
    .Select(c => new SelectListItem
    {
      Value = c.Id.ToString(),
      Text = c.Name
    })
    .ToList();
    ViewBag.galleries = selectListGalleries;

    ViewBag.artist = artist;
    var categories = await _categoryRepository.ListAsync();
    List<SelectListItem> selectListCategories = categories
    .Select(c => new SelectListItem
    {
      Value = c.Id.ToString(),
      Text = c.Name
    })
    .ToList();
    ViewBag.categories = selectListCategories;

    return View();
  }




  // POST: Artworks/Create
  //[HttpPost]
  [HttpPost("createArtwork")]
  [ValidateAntiForgeryToken]
  public async Task<IActionResult> CreateArtworkAsync( ArtworkValueObject artworkValueObject)
  {
    string? identityGuid = _userManager.GetUserId(HttpContext.User);
    var spec = new ArtistByIdentityGuidSpec(identityGuid);
    var artist = await _artistRepository.FirstOrDefaultAsync(spec);
    if (artist == null)
    {
      return NotFound();
    }
    artworkValueObject.Status = ArtworkStatus.Available;
    artworkValueObject.ArtistId = artist.Id;
    //artworkValueObject.Artist = artist;

    string filename = UploadFile(artworkValueObject);
    artworkValueObject.Image = filename;

    var specCategory = new CategoryByIdSpec(artworkValueObject.CategoryId);
    var specGallery = new GalleryByIdSpec(artworkValueObject.GalleryId);
    //artworkValueObject.Category = await _categoryRepository.FirstOrDefaultAsync(specCategory);
    var gallery = await _galleryRepository.FirstOrDefaultAsync(specGallery);
    if (gallery == null) { return NotFound(); }
    var artwork = new Artwork(artworkValueObject);

    if (ModelState.IsValid)
    {
      artist.addArtwork(artwork);
      //var gallery = artworkValueObject.Gallery;
     // await _galleryRepository.UpdateAsync(gallery);
     // await _galleryRepository.SaveChangesAsync();
      await _artistRepository.UpdateAsync(artist);
      await _artistRepository.SaveChangesAsync();
      return RedirectToAction(nameof(MyArtworks));
    }
    return View(artist);
  }

  private string UploadFile(ArtworkValueObject artworkVO)
  {
    string filename = "";
    if (artworkVO.theImage != null)
    {
      string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "ArtworkImages");
      filename = Guid.NewGuid().ToString() + "_" + artworkVO.theImage.FileName;
      string filepath = Path.Combine(uploadDir, filename);
      using (var fileStream = new FileStream(filepath, FileMode.Create))
      {
        artworkVO.theImage.CopyTo(fileStream);
      }
    }
    return filename;

  }


  ///Artwork
  [HttpGet("myArtworks/editArtwork/{artworkId:int}")]
  public async Task<IActionResult> EditArtwork (int artworkId) {
    ///make sure the user is the artwork artist

    string? identityGuid = _userManager.GetUserId(HttpContext.User);
    var spec = new ArtistByIdentityGuidSpec(identityGuid);
    var artist = await _artistRepository.FirstOrDefaultAsync(spec);
    if (artist == null)
    {
      return NotFound();
    }

    List<SelectListItem> selectListGalleries = artist.Galleries
    .Select(c => new SelectListItem
    {
      Value = c.Id.ToString(),
      Text = c.Name
    })
    .ToList();
    ViewBag.galleries = selectListGalleries;

    ViewBag.artist = artist.Id;
    var categories = await _categoryRepository.ListAsync();
    List<SelectListItem> selectListCategories = categories
    .Select(c => new SelectListItem
    {
      Value = c.Id.ToString(),
      Text = c.Name
    })
    .ToList();
    ViewBag.categories = selectListCategories;

src/InteractiveGallery.Web/Areas/AdminArea/Views/Shared/MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Quixlab - Bootstrap Admin Dashboard Template by Themefisher.com</title>
	<!-- Favicon icon -->
	<link rel="icon" type="image/png" sizes="16x16" href="~/images/favicon.png">
	<!-- Custom Stylesheet -->
	<link href="~/css/style.css" rel="stylesheet">

</head>

<body>

	<!--*******************
		Preloader start
	********************-->
	@*<div id="preloader">
	<div class="loader">
	<svg class="circular" viewBox="25 25 50 50">
	<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
	</svg>
	</div>
	</div>*@
	<!--*******************
		Preloader end
	********************-->
	<!--**********************************
		Main wrapper start
	***********************************-->
	<div id="main-wrapper">

		<!--**********************************
			Nav header start
		***********************************-->
		<div class="nav-header">
			<div class="brand-logo">
				<a href="index.html">
					<b class="logo-abbr"><img src="~/images/logo.png" alt=""> </b>
					<span class="logo-compact"><img src="~/images/logo-compact.png" alt=""></span>
					<span class="brand-title">
						<img src="~/images/logo-text.png" alt="">
					</span>
				</a>
			</div>
		</div>
		<!--**********************************
			Nav header end
		***********************************-->









		<div class="header">
			<div class="header-content clearfix">

				<div class="nav-control">
					<div class="hamburger">
						<span class="toggle-icon"><i class="icon-menu"></i></span>
					</div>
				</div>
				<div class="header-left">
					<div class="input-group icons">
						<div class="input-group-prepend">
							<span class="input-group-text bg-transparent border-0 pr-2 pr-sm-3" id="basic-addon1"><i class="mdi mdi-magnify"></i></span>
						</div>
						<input type="search" class="form-control" placeholder="Search Dashboard" aria-label="Search Dashboard">
						<div class="drop-down   d-md-none">
							<form action="#">
								<input type="text" class="form-control" placeholder="Search">
							</form>
						</div>
					</div>
				</div>
				<div class="header-right">
					<ul class="clearfix">
						<li class="icons dropdown">
							<a href="javascript:void(0)" data-toggle="dropdown">
								<i class="mdi mdi-email-outline"></i>
								<span class="badge gradient-1 badge-pill badge-primary">3</span>
							</a>
							<div class="drop-down animated fadeIn dropdown-menu">
								<div class="dropdown-content-heading d-flex justify-content-between">
									<span class="">3 New Messages</span>

								</div>
								<div class="dropdown-content-body">
									<ul>
										<li class="notification-unread">
											<a href="javascript:void()">
												<img class="float-left mr-3 avatar-img" src="~/images/avatar/1.jpg" alt="">
												<div class="notification-content">
													<div class="notification-heading">Saiful Islam</div>
													<div class="notification-timestamp">08 Hours ago</div>
													<div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
												</div>
											</a>
										</li>
										<li class="notification-unread">
											<a href="javascript:void()">
												<img class="float-left mr-3 avatar-img" src="~/images/avatar/2.jpg" alt="">
												<div class="notification-content">
													<div class="notification-heading">Adam Smith</div>
													<div class="notification-timestamp">08 Hours ago</div>
													<div class="notification-text">Can you do me a favour?</div>
												</div>
											</a>
										</li>
										<li>
											<a href="javascript:void()">
												<img class="float-left mr-3 avatar-img" src="~/images/avatar/3.jpg" alt="">
												<div class="notification-content">
													<div class="notification-heading">Barak Obama</div>
													<div class="notification-timestamp">08 Hours ago</div>
													<div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
												</div>
											</a>
										</li>
										<li>
											<a href="javascript:void()">
												<img class="float-left mr-3 avatar-img" src="~/images/avatar/4.jpg" alt="">
												<div class="notification-content">
													<div class="notification-heading">Hilari Clinton</div>
													<div class="notification-timestamp">08 Hours ago</div>
													<div class="notification-text">Hello</div>
												</div>
											</a>
										</li>
									</ul>

								</div>
							</div>
						</li>
						<li class="icons dropdown">
							<a href="javascript:void(0)" data-toggle="dropdown">
								<i class="mdi mdi-bell-outline"></i>
								<span class="badge badge-pill gradient-2 badge-primary">3</span>
							</a>
							<div class="drop-down animated fadeIn dropdown-menu dropdown-notfication">
								<div class="dropdown-content-heading d-flex justify-content-between">
									<span class="">2 New Notifications</span>

								</div>
								<div class="dropdown-content-body">
									<ul>
										<li>
											<a href="javascript:void()">
												<span class="mr-3 avatar-icon bg-success-lighten-2"><i class="icon-present"></i></span>
												<div class="notification-content">
													<h6 class="notification-heading">Events near you</h6>
													<span class="notification-text">Within next 5 days</span>
												</div>
											</a>
										</li>
										<li>
											<a href="javascript:void()">
												<span class="mr-3 avatar-icon bg-danger-lighten-2"><i class="icon-present"></i></span>
												<div class="notification-content">
													<h6 class="notification-heading">Event Started</h6>
													<span class="notification-text">One hour ago</span>
												</div>
											</a>
										</li>
										<li>
											<a href="javascript:void()">
												<span class="mr-3 avatar-icon bg-success-lighten-2"><i class="icon-present"></i></span>
												<div class="notification-content">
													<h6 class="notification-heading">Event Ended Successfully</h6>
													<span class="notification-text">One hour ago</span>
												</div>
											</a>
										</li>
										<li>
											<a href="javascript:void()">
												<span class="mr-3 avatar-icon bg-danger-lighten-2"><i class="icon-present"></i></span>
												<div class="notification-content">
													<h6 class="notification-heading">Events to Join</h6>
													<span class="notification-text">After two days</span>
												</div>
											</a>
										</li>
									</ul>

								</div>
							</div>
						</li>
						<li class="icons dropdown d-none d-md-flex">
							<a href="javascript:void(0)" class="log-user" data-toggle="dropdown">
								<span>English</span>  <i class="fa fa-angle-down f-s-14" aria-hidden="true"></i>
							</a>
							<div class="drop-down dropdown-language animated fadeIn  dropdown-menu">
								<div class="dropdown-content-body">
									<ul>
										<li><a href="javascript:void()">English</a></li>
										<li><a href="javascript:void()">Dutch</a></li>
									</ul>
								</div>
							</div>
						</li>
						<li class="icons dropdown">
							<div class="user-img c-pointer position-relative" data-toggle="dropdown">
								<span class="activity active"></span>
								<img src="~/images/user/1.png" height="40" width="40" alt="">
							</div>
							<div class="drop-down dropdown-profile   dropdown-menu">
								<div class="dropdown-content-body">
									<ul>
										<li>
											<a href="~/app-profile.html"><i class="icon-user"></i> <span>Profile</span></a>
										</li>
										<li>
											<a href="~/email-inbox.html"><i class="icon-envelope-open"></i> <span>Inbox</span> <div class="badge gradient-3 badge-pill badge-primary">3</div></a>
										</li>

										<hr class="my-2">
										<li>
											<a href="~/page-lock.html"><i class="icon-lock"></i> <span>Lock Screen</span></a>
										</li>
										<li><a href="~/page-login.html"><i class="icon-key"></i> <span>Logout</span></a></li>
									</ul>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!--**********************************
			Header end ti-comment-alt
		***********************************-->
		<!--**********************************
			Sidebar start
		***********************************-->
		<div class="nk-sidebar">
			<div class="nk-nav-scroll">
				<ul class="metismenu" id="menu">

					<li>
                        <a href="@Url.Action("Index","Galleries",new { area = "AdminArea" })" aria-expanded="false">
                            <i class="icon-badge menu-icon"></i><span class="nav-text">Galleries</span>
						</a>
					</li>

					<li>
                        <a href="@Url.Action("Index","Artists",new { area = "AdminArea" })" aria-expanded="false">
                            <i class="icon-badge menu-icon"></i><span class="nav-text">Artists</span>
						</a>
					</li>



                    <li>
                        <a href="@Url.Action("Index","Categories",new { area = "AdminArea" })" aria-expanded="false">
                            <i class="icon-badge menu-icon"></i><span class="nav-text">Artists</span>
                        </a>
                    </li>


				</ul>
			</div>
		</div>
		<!--**********************************
			Sidebar end
		***********************************-->
		<!--**********************************
			Content body start
		***********************************-->
		<div class="content-body">

			<div class="container-fluid">

				@RenderBody()

			</div>
			<!-- #/ container -->
		</div>
		<!--**********************************
			Content body end
		***********************************-->
		<!--**********************************
			Footer start
		***********************************-->
		<div class="footer">
			<div class="copyright">
				<p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
			</div>
		</div>
		<!--**********************************
			Footer end
		***********************************-->
	</div>
	<!--**********************************
		Main wrapper end
	***********************************-->
	<!--**********************************
		Scripts
	***********************************-->
	<script src="~/plugins/common/common.min.js"></script>
	<script src="~/js/custom.min.js"></script>
	<script src="~/js/settings.js"></script>
	<script src="~/js/gleek.js"></script>
	<script src="~/js/styleSwitcher.js"></script>
</body>

</html>

src/InteractiveGallery.Web/Areas/AdminArea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Clean.Architecture.Web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Clean.Architecture.Web.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clean.Architecture.Web</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>
	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; @DateTime.Today.Year - Clean.Architecture.Web
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>