src/InteractiveGallery.Web/Areas/AdminArea/Controllers/GalleriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InteractiveGallery.Core.GalleryAggregate;
using InteractiveGallery.Infrastructure.Data;
using InteractiveGallery.Core.ArtistAggregate;
using InteractiveGallery.SharedKernel.Interfaces;
using InteractiveGallery.Core.ArtistAggregate.Specifications;
using InteractiveGallery.Core.GalleryAggregate.Specifications;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using InteractiveGallery.Core.CategoryAggregate;
using InteractiveGallery.Core.CategoryAggregate.Specifications;

namespace InteractiveGallery.Web.Areas.AdminArea.Controllers;
[Area("AdminArea")]
[Route("AdminArea/[controller]")]
[Authorize(Roles = "Admin")]
public class GalleriesController : Controller
    {
  private readonly IRepository<Gallery> _galleryRepository;
  private readonly IRepository<Artist> _artistRepository;
  private readonly IRepository<Category> _categoryRepository;
  private readonly UserManager<ApplicationUser> _userManager;


  public GalleriesController(IRepository<Gallery> galleryRepository, IRepository<Artist> artistRepository, IRepository<Category> categoryRepository,UserManager<ApplicationUser> userManager)
  {
    _galleryRepository = galleryRepository;
    _artistRepository = artistRepository;
    _userManager = userManager;
    _categoryRepository = categoryRepository;
  }


  // GET: Galleries
  [HttpGet]
  public async Task<IActionResult> Index()
        {
    var galleries = await _galleryRepository.ListAsync();
  
    return View(galleries.ToArray());
  }

  [HttpGet("details/{id:int}")]
  public async Task<IActionResult> Details(int id)
  {
    var spec = new GalleryByIdSpec(id);
    var gallery = await _galleryRepository.FirstOrDefaultAsync(spec);
    if (gallery == null)
    {
      return NotFound();
    }
    var artistSpec = new ArtistByIdSpec(gallery.InitiatorId);
    var artist = await _artistRepository.FirstOrDefaultAsync(artistSpec);
    var galleryVO = new GalleryValueObject
    {
      Id = gallery.Id,
      Name = gallery.Name,
      Theme = gallery.Theme,
      InitiatorId = gallery.InitiatorId,
      InitiatorArtist = artist,
      Artworks = gallery.Artworks
    };
    return View(galleryVO);
  }



  // GET: Galleries/Details/5
  [HttpGet("detailsGallery")]
  public  IActionResult DetailsGallery()
  {
    return View();
  }

  // GET: Galleries/Create
  [HttpGet("create")]
  public async Task<IActionResult> CreateAsync()
        {
    var artists = await _artistRepository.ListAsync();
    List<SelectListItem> selectListGalleries = artists
    .Select(c => new SelectListItem
    {
      Value = c.Id.ToString(),
      Text = c.Name
    })
    .ToList();
    ViewBag.artists = selectListGalleries;
    return View();
        }

  // POST: Galleries/Create
  // To protect from overposting attacks, enable the specific properties you want to bind to.
  // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
  [HttpPost("create")]
  [ValidateAntiForgeryToken]
  public async Task<IActionResult> Create(GalleryValueObject galleryValueObject)
        {
    var artistSpec = new ArtistByIdSpec(galleryValueObject.InitiatorId);
    var artist = await _artistRepository.FirstOrDefaultAsync(artistSpec);
    galleryValueObject.InitiatorArtist = artist;
    var gallery = new Gallery(galleryValueObject);
    
    if (ModelState.IsValid)
    {
      await _galleryRepository.AddAsync(gallery);
      await _galleryRepository.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }
            return View(gallery);
        }

  // GET: Galleries/Edit/5
  [HttpGet("edit/{id:int}")]
  public async Task<IActionResult> Edit(int id)
        {

    var spec = new GalleryByIdSpec(id);
    var gallery = await _galleryRepository.FirstOrDefaultAsync(spec);
    if (gallery == null)
    {
      return NotFound();
    }
    var artistSpec= new ArtistByIdSpec(gallery.InitiatorId);
    var artist = await _artistRepository.FirstOrDefaultAsync(artistSpec);
    var galleryVO = new GalleryValueObject
    {
      Id = gallery.Id,
      Name = gallery.Name,
      Theme = gallery.Theme,
      InitiatorId = gallery.InitiatorId,
      InitiatorArtist = artist
    };
    return View(galleryVO);
  }

  // POST: Galleries/Edit/5
  // To protect from overposting attacks, enable the specific properties you want to bind to.
  // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
  [HttpPost("edit/{id:int}")]
  [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Theme,InitiatorArtist,InitiatorId,Id")] GalleryValueObject galleryValueObject)
        {
    if (id != galleryValueObject.Id)
    {
      return NotFound();
    }

    if (ModelState.IsValid)
    {
      var spec = new GalleryByIdSpec(id);
      var gallery = await _galleryRepository.FirstOrDefaultAsync(spec);
      if (gallery == null) { return NotFound(); }
      gallery.updateGallery(galleryValueObject);
      await _galleryRepository.UpdateAsync(gallery);
      await _galleryRepository.SaveChangesAsync();

      return RedirectToAction(nameof(Index));
    }
    return View(galleryValueObject);
  }


  // GET: Galleries/Delete/5
  [HttpGet("delete/{id:int}")]
  public async Task<IActionResult> Delete(int id)
        {

    var spec = new GalleryByIdSpec(id);
    var gallery = await _galleryRepository.FirstOrDefaultAsync(spec);
    if (gallery == null)
    {
      return NotFound();
    }
    await _galleryRepository.DeleteAsync(gallery);
    var artistSpec = new ArtistByIdSpec(gallery.InitiatorId);
    var artist = await _artistRepository.FirstOrDefaultAsync(artistSpec);
    var galleryVO = new GalleryValueObject
    {

      Id = gallery.Id,
      Name = gallery.Name,
      Theme = gallery.Theme,
      InitiatorId = gallery.InitiatorId,
      InitiatorArtist = artist
    };
    return View(galleryVO);
  }

  // POST: Galleries/Delete/5
  [HttpPost("delete/{id:int}")]
  [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

    var spec = new GalleryByIdSpec(id);

    var gallery = await _galleryRepository.FirstOrDefaultAsync(spec);
    if (gallery != null)
    {
      await _galleryRepository.DeleteAsync(gallery);
    }

    await _galleryRepository.SaveChangesAsync();
    return RedirectToAction(nameof(Index));
  }
//  [HttpGet("{galleryId:int}/editArtworkModal/{artworkId:int}")]
  //[HttpGet]
  public async Task<IActionResult> EditArtworkModal(int galleryId, int artworkId)
  {
    var spec = new GalleryByIdSpec(galleryId);
    var gallery = await _galleryRepository.FirstOrDefaultAsync(spec);
    if(gallery==null)return NotFound();
    var artwork = gallery.getArtworkById(artworkId);
    var artworkVO = new ArtworkValueObject(artwork);

    return PartialView("EditArtworkModal",
        artworkVO
        );
  }
 // [HttpPost("/{galleryId:int}/editArtworkModal/{artworkId:int}")]
  //[HttpPost]
  public async Task<IActionResult> EditArtworkModal(int galleryId,int artworkId, [Bind("Name,Price,Status,CategoryId,ArtistId,GalleryId,Image,Description,Id")] ArtworkValueObject artworkVO)
  {
    if (artworkVO == null) return NotFound();
    if (artworkId != artworkVO.Id)
    {
      return NotFound();
    }
    if (ModelState.IsValid)
    {
    var spec = new GalleryByIdSpec(galleryId);
    var gallery = await _galleryRepository.FirstOrDefaultAsync(spec);
    if (gallery == null) return NotFound();
      gallery.updateArtwork(artworkVO);
      return RedirectToAction(nameof(Index));
    }
    return View(artworkVO);
  }

  [HttpGet("details/{galleryId:int}/editArtwork/{artworkId:int}")]
  public async Task<IActionResult> EditArtwork(int galleryId,int artworkId)
  {
    var spec = new GalleryByIdSpec(galleryId);
    var gallery = await _galleryRepository.FirstOrDefaultAsync(spec);
    if (gallery == null) return NotFound();
    var artwork = gallery.getArtworkById(artworkId);
    var artworkVO = new ArtworkValueObject(artwork);
    if (artwork.ArtistId == null) return NotFound();
    int artistid = (int)artwork.ArtistId;
    var artistspec = new ArtistByIdSpec(artistid);
    var artist = await _artistRepository.FirstOrDefaultAsync(artistspec);
    if (artist == null) return NotFound();


    List<SelectListItem> selectListGalleries = artist.Galleries
    .Select(c => new SelectListItem
    {
      Value = c.Id.ToString(),
      Text = c.Name
    })
    .ToList();
    ViewBag.galleries = selectListGalleries;

    ViewBag.artist = artist.Id;
    var categories = await _categoryRepository.ListAsync();
    List<SelectListItem> selectListCategories = categories
    .Select(c => new SelectListItem
    {
      Value = c.Id.ToString(),
      Text = c.Name
    })
    .ToList();
    ViewBag.categories = selectListCategories;

    return View(artworkVO);
  }

  // POST: Artworks/Edit/5
  // To protect from overposting attacks, enable the specific properties you want to bind to.
  // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
  [HttpPost("details/{galleryId:int}/editArtwork/{artworkId:int}")]
  [ValidateAntiForgeryToken]
  public async Task<IActionResult> EditArtwork(int galleryId,int artworkId, [Bind("Name,Price,Status,CategoryId,ArtistId,GalleryId,Image,Description,Id")] ArtworkValueObject artworkVO)
  { if (artworkId != artworkVO.Id) return NotFound();
    if (ModelState.IsValid) { 
    var spec = new GalleryByIdSpec(galleryId);
    var gallery = await _galleryRepository.FirstOrDefaultAsync(spec);
    if (gallery == null) return NotFound();
    var artistspec = new ArtistByIdSpec(artworkVO.ArtistId);
    var artist = await _artistRepository.FirstOrDefaultAsync(artistspec);
    if (artist == null) return NotFound();
    var catgoryspec = new CategoryByIdSpec(artworkVO.CategoryId);

src/InteractiveGallery.Web/Areas/UserArea/Views/Galleries/ArtworkDetails.cshtml
@model InteractiveGallery.Core.ArtistAggregate.ArtworkValueObject
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/UserArea/Views/Shared/MyLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Artwork</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        @*       <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Gallery)
        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Gallery.Name)
        </dd>
        <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Artist.Name)
        </dd>*@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/InteractiveGallery.Web/Areas/UserArea/Views/Galleries/Create.cshtml
@model InteractiveGallery.Core.GalleryAggregate.GalleryValueObject
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Create";
	Layout = "~/Areas/UserArea/Views/Shared/MyLayout.cshtml";
}

<h1>Create</h1>


<div class="col-lg-12">
	<div class="card">
		<div class="card-body">
			<h4 class="card-title">Create new gallery</h4>
			<div class="basic-form">
				<form asp-action="Create">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group row">
						<label asp-for="Name" class="col-sm-2 col-form-label"></label>
						<div class="col-sm-10">
							<input asp-for="Name" class="form-control" />
							<span asp-validation-for="Name" class="text-danger"></span>
						</div>
					</div>

					<div class="form-group row">
						<label asp-for="Theme" class="col-sm-2 col-form-label"></label>
						<div class="col-sm-10">
							<input asp-for="Theme" class="form-control" />
							<span asp-validation-for="Theme" class="text-danger"></span>
						</div>
					</div>

					<input type="submit" value="Create" class="btn mb-1 btn-flat btn-outline-primary"/>
					<a asp-action="Index" class="card-text">Back to List</a>
				</form>
			</div>
		</div>
		<div>
	
		</div>
	</div>
</div> 

src/InteractiveGallery.Web/Areas/UserArea/Views/Galleries/Delete.cshtml
@model InteractiveGallery.Core.GalleryAggregate.GalleryValueObject
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/UserArea/Views/Shared/MyLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this gallery?</h3>
<div>
	<h4>Gallery</h4>
	<div class="col-md-6 col-lg-12">
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">@Html.DisplayFor(model => model.Name)</h5>
				<p class="card-text">Artist @Html.DisplayFor(model => model.InitiatorArtist.Name)</p>
				<p class="card-text">Theme @Html.DisplayFor(model => model.Theme)</p>
				<pr>
					<p class="card-text">Artworks</p>

					@*	@foreach (var item in Model.Artworks)
					{
						<div class="col-md-6 col-lg-3">
							<div class="card">
								
								<img class="img-fluid" src="../images/big/img1.jpg" alt="">
								<div class="card-body">
									<h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
									<p class="card-text">Artist @Html.DisplayFor(modelItem => item.Description)</p>
									<p class="card-text">Theme @Html.DisplayFor(modelItem => item.Price)</p>
								</div>
								<div>
								</div>
							</div>
						</div>
					}*@

					<form asp-action="Delete">
						<input type="hidden" asp-for="Id" />
						<input type="submit" value="Delete" class="btn btn-danger" /> |
						<a asp-action="Index">Back to List</a>
					</form>

			</div>
		</div>
	</div>
</div>
    

src/InteractiveGallery.Web/Areas/UserArea/Views/Galleries/DeleteArtwork.cshtml
@model InteractiveGallery.Core.ArtistAggregate.Artwork
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "DeleteArtwork";
    Layout = "~/Areas/UserArea/Views/Shared/MyLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artwork</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gallery)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gallery.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>
    </dl>

    <form asp-action="DeleteArtwork">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/InteractiveGallery.Web/Areas/UserArea/Views/Galleries/Details.cshtml
@model InteractiveGallery.Core.GalleryAggregate.GalleryValueObject
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Details";
	Layout = "~/Areas/UserArea/Views/Shared/MyLayout.cshtml";
}



<br />
			<h4 class="card-title">@Html.DisplayFor(model => model.Name) Gallery</h4>
                <ul class="card-profile__info">
                    <li class="mb-1"> <strong class="text-dark mr-4">Artist</strong><span>@Html.DisplayFor(model => model.InitiatorArtist.Name)</span></li>
                    <li><strong class="text-dark mr-4">Theme</strong><span>@Html.DisplayFor(model => model.Theme)</span></li>
                </ul>
           
	
<br>

        <h4>   Artworks</h4>
    <br>
<div class="bootstrap-modal">

    <button id="addArtworkButton" data-toggle="modal" data-target="#artworkModal" onclick="showModal(@Model.Id)">Add Artwork</button>

    <!-- Modal -->
    <div class="modal fade" id="artworkModal" tabindex="-1" role="dialog" aria-labelledby="artworkModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="artworkModalLabel">Select Artworks to Add</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="artworkModalBody">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="submitArtworks" onclick="submitArtworks(@Model.Id)">Add Selected Artworks</button>
                </div>
            </div>
        </div>
    </div>
</div>

        
<br><br />
 <div class="row"> 
            @foreach (var item in Model.Artworks)
            {
                <div class="col-md-6 col-lg-3">
                    <div class="card">
                        @*imaaaage sides aren;t rounded*@
                    <img src="~/ArtworkImages/@item.Image" asp-append-version="true"style="height:300px" class="img-fluid">

                        <div class="card-body">
                                <h4 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h4>

                                <ul class="card-profile__info">
                                    <li class="mb-1"> <strong class="text-dark mr-4">Description</strong><span>@Html.DisplayFor(modelItem => item.Description)</span></li>
                                    <li><strong class="text-dark mr-4">Price</strong><span>@Html.DisplayFor(modelItem => item.Price)</span></li>
                                </ul>
                    <a href="@Url.Action("EditArtwork","Galleries",new { area = "UserArea" ,artworkId=item.Id,galleryId=Model.Id})" type="button" class="btn mb-1 btn-flat btn-outline-primary">Edit</a>
                    <a href="@Url.Action("DeleteArtwork","Galleries",new { area = "UserArea" ,artworkId=item.Id,galleryId=Model.Id})" type="button" class="btn mb-1 btn-flat btn-outline-danger">Delete</a>

                </div>             
                    </div>
                </div>

            }
					
        </div>

<script>
    
        function showModal(id) {
            console.log("ss");
            
        var aurl = '@Url.Content("~/UserArea/Galleries/details/")' + parseInt(id)+ "/AddArtwork";
        
  
            $.ajax({
            url: aurl,
                type: "GET",
                success: function (data) {
                $("#artworkModalBody").html(data);
                $('.modal').modal('show');
                }

            });
        }


    
</script>

<script>

    function submitArtworks(id) {
       // JSON
        var selectedArtworks = [];
        $(".artwork-checkbox:checked").each(function () {
            selectedArtworks.push($(this).val());
        });

        var intIds = selectedArtworks.map(a =>  parseInt(a));
        console.log(intIds);
        var aurl = '@Url.Content("~/UserArea/Galleries/details/")' + parseInt(id) + "/AddArtwork";
        console.log(selectedArtworks);

        $.ajax({
            url: aurl,
            contentType: "application/json",
            type: "POST",
            data: JSON.stringify(intIds),
            success: function (response) {
                console.log(response);
                // taost success
                // when ok clicked, hide modal
            },
            error: function(xhr, status, error) {
                // toast error
                // try to refresh and try again
                // hide modal on ok click
                // 
            }
        });
        
    }

</script>

src/InteractiveGallery.Web/Areas/UserArea/Views/Galleries/Edit.cshtml
@model InteractiveGallery.Core.GalleryAggregate.GalleryValueObject
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/UserArea/Views/Shared/MyLayout.cshtml";
}
<h1>Edit</h1>


<div class="col-lg-12">
	<div class="card">
		<div class="card-body">
			<h4 class="card-title">Edit my gallery</h4>
			<div class="basic-form">
				<form asp-action="Edit">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group row">
						<label asp-for="Name" class="col-sm-2 col-form-label"></label>
						<div class="col-sm-10">
							<input asp-for="Name" class="form-control" />
							<span asp-validation-for="Name" class="text-danger"></span>
						</div>
					</div>

					<div class="form-group row">
						<label asp-for="Theme" class="col-sm-2 col-form-label"></label>
						<div class="col-sm-10">
							<input asp-for="Theme" class="form-control" />
							<span asp-validation-for="Theme" class="text-danger"></span>
						</div>
					</div>
					<input type="hidden" asp-for="Id" />
					<input type="hidden" asp-for="InitiatorArtist" />
					<input type="hidden" asp-for="InitiatorId" />
					<input type="submit" value="Save" class="btn btn-danger" />
					<a asp-action="Index" class="card-text">Back to List</a>
				</form>
			</div>
		</div>
		<div>
		</div>
	</div>
</div>

src/InteractiveGallery.Web/Areas/UserArea/Views/Galleries/Index.cshtml
@model IEnumerable<InteractiveGallery.Core.GalleryAggregate.Gallery>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
	Layout = "~/Areas/UserArea/Views/Shared/MyLayout.cshtml";
}

<h1>Galleries</h1>
<br>
<div class="row">
    @{
        @foreach (var item in ViewBag.nonEmptyGalleries)
	{

            <div class="col-md-6 col-lg-3">

                <div class="card">
                    <img class ="img-fluid" >
                    <div class="card-body">
					<h5 class="card-title"> @item.Name </h5>
                    <p class="card-text">Artist: @item.InitiatorArtist.Name </p>
					<p class="card-text">Theme: @item.Theme</p>
                    <h5><a asp-action="VisitGallery" asp-route-id="@item.Id">Visit Gallery</a></h5>
				</div>
			</div>
		
                </div>
            }

      }     
    
    
</div>

src/InteractiveGallery.Web/Areas/UserArea/Views/Galleries/MyGalleries.cshtml
@model IEnumerable<InteractiveGallery.Core.GalleryAggregate.Gallery>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "MyIndex";
    Layout = "~/Areas/UserArea/Views/Shared/MyLayout.cshtml";
}
<h1>My Galleries</h1>
<br>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-6 col-lg-3">

            <a asp-action="Details" asp-route-id="@item.Id">
                <div class="card" style="height:200px">
                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
          				<p class="card-text">Theme: @Html.DisplayFor(modelItem => item.Theme)</p>
                          <br>
                        <a asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn mb-1 btn-flat btn-outline-primary">Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" type="button" class="btn mb-1 btn-flat btn-outline-danger">Delete</a>
                        <a asp-action="VisitGallery" asp-route-id="@item.Id" class="btn mb-1 btn-flat btn-outline-success">Visit Gallery</a>

                </div>
                </div>
            </a>
        </div>
    }

    <div class="col-md-6 col-lg-3">
        <a asp-action="Create" aria-expanded="false">
            <div class="card" style="height:200px">
                <div class="card-body">
                    <br><br><br>

                    <h4 class="card-title">Create new gallery</h4>
                    <br><br>
                </div>
            </div>
        </a>
    </div>

</div>